version: '3'

services:
  sidsteam:
    build:
      context: .
      args:
        steam_user: "${STEAM_USER}"
        steam_uid: "${STEAM_UID}"
    image: eartiaga/sidsteam
    network_mode: bridge
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
      - $XDG_RUNTIME_DIR/pulse:/run/user/1000/pulse
      # Persistent directory for steam data
      - ${STEAM_DATADIR:-./data}:/home/${STEAM_USER:-steam}
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-modeset
      - /dev/dri
      - /dev/snd
      - /dev/sr0
    environment:
      - DISPLAY=unix$DISPLAY
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
      - STEAM_SKIP=${STEAM_SKIP:-no}
    shm_size: 4G

