version: '3'

services:
  sidsteam:
    privileged: true
    build:
      context: .
      args:
        STEAM_USER: "${STEAM_USER:-steam}"
        STEAM_UID: "${STEAM_UID:-1001}"
    image: eartiaga/sidsteam
    network_mode: bridge
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
      - $XDG_RUNTIME_DIR/pulse:/run/user/${STEAM_UID:-1001}/pulse
      - ${STEAM_DATADIR:-./data}:/home/${STEAM_USER:-steam}
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-modeset
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/dri
      - /dev/snd
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:-/run/user/1001}/pulse/native
      - STEAM_ACTION=${STEAM_ACTION:-default}
    shm_size: 4G
