#!/bin/bash

# Log everything to stdout
exec 2>&1

export DATADIR="$HOME"

# Bail out on failure
set -e

case "$STEAM_ACTION" in
    wait)
        zenity --info --text="Steam Docker on stand-by. Click OK to terminate."
        wait
        ;;
    shell)
        x-terminal-emulator
        wait
        ;;
    custom)
        if [ -x "$DATADIR/launch.rc" ]; then
            echo "running custom user launcher..."
            source "$DATADIR/launch.rc"
        fi
        wait
        ;;
    *)
        # Start steam
        echo "starting steam..."
        /usr/bin/steam
        wait
        echo "steam terminated"
        ;;
esac

